alias gs='git status'
alias ga='git add'
alias gcm='git commit -m'
alias gp='git push'
alias gcl='git clone'
alias gpu='git pull'
alias gpuo='git pull origin'
alias gpo='git push origin'
alias gch='git checkout'
alias gcb='git checkout -b'
alias docb='docker compose build'
alias docu='docker compose up'
alias docd='docker compose down'

alias docrmi='docker rmi $(docker images -q)'
alias docstp='docker stop $(docker ps -a -q)'
alias docrm='docker rm $(docker ps -a -q)'

alias pn='pnpm'
